import os
import datetime
import re
from jinja2 import Template
from rich.console import Console
from rich.panel import Panel

console = Console()

# HTML Template with Embedded Vis.js for Network Graphing
TEMPLATE_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
    <style>
        :root {
            --bg-color: #0d1117;
            --card-bg: #161b22;
            --text-color: #c9d1d9;
            --accent-color: #58a6ff;
            --border-color: #30363d;
            --alert-color: #ff7b72;
            --success-color: #2ea043;
        }
        body {
            background-color: var(--bg-color);
            color: var(--text-color);
            font-family: 'Consolas', 'Monaco', monospace;
            margin: 0;
            padding: 20px;
        }
        .container { max-width: 1400px; margin: 0 auto; }
        .header {
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 20px;
            margin-bottom: 30px;
            text-align: center;
        }
        .header h1 { color: var(--alert-color); margin: 0; letter-spacing: 2px; }
        
        /* Network Map Container */
        #network-map {
            width: 100%;
            height: 500px;
            border: 1px solid var(--border-color);
            background: #000;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .metric-card {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            padding: 20px;
            border-radius: 6px;
            text-align: center;
        }
        .metric-val { font-size: 2em; font-weight: bold; color: #fff; }
        
        .log-section {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .log-header {
            padding: 10px 20px;
            background: #21262d;
            border-bottom: 1px solid var(--border-color);
            font-weight: bold;
            color: var(--accent-color);
        }
        .log-content {
            padding: 15px;
            overflow-x: auto;
            white-space: pre-wrap;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>DAVOID // THREAT MAP</h1>
            <p>INTELLIGENCE REPORT | {{ timestamp }}</p>
        </div>

        <div id="network-map"></div>

        <div class="summary-grid">
            <div class="metric-card">
                <div class="metric-val">{{ unique_ips }}</div>
                <div>Unique Targets Identified</div>
            </div>
            <div class="metric-card">
                <div class="metric-val">{{ logs|length }}</div>
                <div>Intelligence Files</div>
            </div>
            <div class="metric-card">
                <div class="metric-val">{{ total_lines }}</div>
                <div>Data Points Extracted</div>
            </div>
        </div>

        <h3>RAW INTELLIGENCE LOGS</h3>
        {% for log in logs %}
        <div class="log-section">
            <div class="log-header">FILE: {{ log.filename }}</div>
            <div class="log-content">{{ log.content }}</div>
        </div>
        {% endfor %}
    </div>

    <script type="text/javascript">
        // Data generated by Python Parser
        var nodes = new vis.DataSet({{ nodes_json }});
        var edges = new vis.DataSet({{ edges_json }});

        var container = document.getElementById('network-map');
        var data = { nodes: nodes, edges: edges };
        var options = {
            nodes: {
                shape: 'dot',
                size: 20,
                font: { size: 14, color: '#ffffff' },
                borderWidth: 2,
                shadow: true
            },
            edges: {
                width: 1,
                color: { color: '#58a6ff', highlight: '#ff7b72' },
                smooth: { type: 'continuous' }
            },
            physics: {
                stabilization: false,
                barnesHut: { gravitationalConstant: -3000 }
            },
            interaction: { hover: true }
        };
        var network = new vis.Network(container, data, options);
    </script>
</body>
</html>
"""


def extract_nodes_from_logs(logs):
    """
    Parses logs to find IP addresses and build a topology graph.
    Returns JSON-serializable nodes and edges for Vis.js.
    """
    ips = set()
    # Regex for IPv4
    ip_pattern = re.compile(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b')

    # 1. Extract all unique IPs from all logs
    for log in logs:
        found = ip_pattern.findall(log['content'])
        for ip in found:
            if ip != "0.0.0.0" and ip != "127.0.0.1":
                ips.add(ip)

    # 2. Build Nodes
    nodes = [{"id": 0, "label": "DAVOID-HQ", "color": "#ff7b72", "size": 30}]
    edges = []

    for idx, ip in enumerate(ips, 1):
        nodes.append({
            "id": idx,
            "label": ip,
            "color": "#2ea043",
            "title": f"Target: {ip}"  # Tooltip
        })
        # Connect everything to HQ for a star topology visualization
        edges.append({"from": 0, "to": idx})

    return nodes, edges


def generate_report():
    console.print(Panel("Generating Visual Threat Map...",
                  title="Reporter", border_style="cyan"))

    log_dir = "logs"
    if not os.path.exists(log_dir):
        console.print("[red][!] No 'logs' directory found.[/red]")
        return

    gathered_logs = []
    total_lines = 0

    for f in os.listdir(log_dir):
        path = os.path.join(log_dir, f)
        if os.path.isfile(path):
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as file_content:
                    content = file_content.read()
                    total_lines += len(content.splitlines())
                    gathered_logs.append({"filename": f, "content": content})
            except:
                pass

    if not gathered_logs:
        return console.print("[yellow][!] No log data.[/yellow]")

    # Extract Graph Data
    nodes, edges = extract_nodes_from_logs(gathered_logs)

    try:
        t = Template(TEMPLATE_HTML)
        html_output = t.render(
            title="Davoid Threat Map",
            timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            logs=gathered_logs,
            total_lines=total_lines,
            unique_ips=len(nodes) - 1,  # Subtract HQ
            nodes_json=nodes,
            edges_json=edges
        )

        timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        report_filename = f"ThreatMap_{timestamp}.html"

        with open(report_filename, "w", encoding="utf-8") as f:
            f.write(html_output)

        console.print(
            f"[bold green][+] Visual Report Generated: {report_filename}[/bold green]")

        # Auto-open
        if os.name == 'posix':
            os.system(
                f"open {report_filename} 2>/dev/null || xdg-open {report_filename} 2>/dev/null")
        elif os.name == 'nt':
            os.startfile(report_filename)

    except Exception as e:
        console.print(f"[red][!] Reporting Error: {e}[/red]")


if __name__ == "__main__":
    generate_report()
