import os
import datetime
import json
from jinja2 import Template
from rich.console import Console
from rich.panel import Panel

console = Console()

# Embedded HTML Template for single-file portability
TEMPLATE_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Davoid Security Assessment Report</title>
    <style>
        :root {
            --bg-color: #0d1117;
            --card-bg: #161b22;
            --text-color: #c9d1d9;
            --accent-color: #58a6ff;
            --border-color: #30363d;
            --alert-color: #ff7b72;
        }
        body {
            background-color: var(--bg-color);
            color: var(--text-color);
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            margin: 0;
            padding: 20px;
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        .header {
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 20px;
            margin-bottom: 30px;
            text-align: center;
        }
        .header h1 { color: var(--alert-color); margin: 0; font-size: 2.5em; letter-spacing: 2px; }
        .header p { color: var(--accent-color); margin-top: 5px; }
        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
        }
        .metric-card {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            padding: 15px;
            border-radius: 6px;
            text-align: center;
        }
        .metric-value { font-size: 1.5em; font-weight: bold; color: #fff; }
        .metric-label { font-size: 0.9em; color: #8b949e; }
        
        .log-section {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 6px;
            margin-bottom: 20px;
            overflow: hidden;
        }
        .log-header {
            background: #21262d;
            padding: 10px 15px;
            border-bottom: 1px solid var(--border-color);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .log-title { font-weight: bold; color: var(--accent-color); }
        .log-content {
            padding: 15px;
            overflow-x: auto;
            white-space: pre-wrap;
            font-size: 0.9em;
            background: #0d1117;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid var(--border-color);
            color: #484f58;
            font-size: 0.8em;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>DAVOID // MISSION REPORT</h1>
            <p>CLASSIFIED SECURITY ASSESSMENT</p>
            <p>Generated: {{ timestamp }}</p>
        </div>

        <div class="summary">
            <div class="metric-card">
                <div class="metric-value">{{ logs|length }}</div>
                <div class="metric-label">Files Analyzed</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ total_lines }}</div>
                <div class="metric-label">Lines of Intel</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ system_user }}</div>
                <div class="metric-label">Operator</div>
            </div>
        </div>

        {% for log in logs %}
        <div class="log-section">
            <div class="log-header">
                <span class="log-title">📄 {{ log.filename }}</span>
                <span style="font-size: 0.8em; color: #8b949e;">{{ log.size }} bytes</span>
            </div>
            <div class="log-content">{{ log.content }}</div>
        </div>
        {% endfor %}

        <div class="footer">
            <p>GENERATED BY DAVOID FRAMEWORK | CONFIDENTIAL</p>
        </div>
    </div>
</body>
</html>
"""


def generate_report():
    console.print(Panel("Initiating Report Generation Sequence...",
                  title="Reporter", border_style="cyan"))

    log_dir = "logs"
    if not os.path.exists(log_dir):
        console.print(
            "[red][!] No 'logs' directory found. Run scans to generate data first.[/red]")
        return

    gathered_logs = []
    total_lines = 0

    # Iterate through all files in the logs directory
    for f in os.listdir(log_dir):
        path = os.path.join(log_dir, f)
        if os.path.isfile(path):
            try:
                size = os.path.getsize(path)
                with open(path, "r", encoding="utf-8", errors="ignore") as file_content:
                    content = file_content.read()
                    line_count = len(content.splitlines())
                    total_lines += line_count

                    gathered_logs.append({
                        "filename": f,
                        "content": content,
                        "size": size
                    })
            except Exception as e:
                console.print(f"[yellow][!] Skipped {f}: {e}[/yellow]")

    if not gathered_logs:
        console.print(
            "[yellow][!] No valid log data found to report.[/yellow]")
        return

    try:
        # Render the template
        t = Template(TEMPLATE_HTML)
        html_output = t.render(
            timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            logs=gathered_logs,
            total_lines=total_lines,
            system_user=os.getenv('USER', os.getenv('USERNAME', 'Unknown'))
        )

        # Save the report
        timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        report_filename = f"Davoid_Report_{timestamp}.html"

        with open(report_filename, "w", encoding="utf-8") as f:
            f.write(html_output)

        console.print(Panel(
            f"[bold green]Report Generated Successfully![/bold green]\n"
            f"[white]Filename:[/white] {report_filename}\n"
            f"[white]Logs Merged:[/white] {len(gathered_logs)}",
            title="Success",
            border_style="green"
        ))

        # Attempt to open the report automatically
        if os.name == 'posix':
            # Linux/macOS
            os.system(
                f"open {report_filename} 2>/dev/null || xdg-open {report_filename} 2>/dev/null")
        elif os.name == 'nt':
            # Windows
            os.startfile(report_filename)

    except Exception as e:
        console.print(f"[red][!] Reporting Critical Failure: {e}[/red]")


if __name__ == "__main__":
    generate_report()
